services:
  - type: web
    name: attrition-predictor
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn rag_predictor:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: GEMINI_API_KEY
        value: <your-gemini-api-key>
